fix multiple financial officer issue
kir-dev/pek-next pull request #391
Opened 2022-05-20 16:48 UTC by SepsiLaszlo

2022-05-23 17:46 UTC, bbucsy requested changes
I would suggest using an other method for data migration.
I think, because data migrations are rare, maybe we would be better use a one-off rake task instead. Or we could pull the data_migration :gem: in the project

There are some reference blog posts about the issue in my comments

2022-05-23 17:46 UTC, bbucsy commented on db/migrate/20220520160742_remove_financial_officers_if_more_then_one.rb
> +class RemoveFinancialOfficersIfMoreThenOne < ActiveRecord::Migration[6.0]
As far as i understand it's generally not best practice to do data migration in db schema migrations.

Sources: [here](https://www.ombulabs.com/blog/rails/data-migrations/three-useful-data-migrations-patterns-in-rails.html) and [here](https://thoughtbot.com/blog/data-migrations-in-rails)

2022-05-23 17:46 UTC, bbucsy commented on db/migrate/20220520160742_remove_financial_officers_if_more_then_one.rb
> +    groups_with_fo_count = Group.joins(memberships: :posts)
If group model changes in some ways, than it can break the migration.

2022-05-26 08:31 UTC, SepsiLaszlo commented
@bbucsy thank you for the suggestion, I moved the logic from the migration into a rake task! :point_right:  :bookmark_tabs:

2022-05-26 09:23 UTC, bbucsy approved these changes

2022-05-28 19:24 UTC, merged